// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvlotgemhepowjwstlys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2bG90Z2VtaGVwb3dqd3N0bHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzc5OTIsImV4cCI6MjA2NjYxMzk5Mn0.IHp1rDNk4OEZt7qUnx1-1AHJNIUGlTcSnEnzZg8n-ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);